blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/zk-evm/bls12-381/discussions
    about: Ask questions, share ideas, and discuss the library with the community
  - name: 🔒 Security Vulnerabilities
    url: mailto:security@zkevm.dev
    about: Report security vulnerabilities privately (DO NOT create public issues)
  - name: 📖 Documentation
    url: https://github.com/zk-evm/bls12-381/blob/main/README.md
    about: Read the comprehensive documentation before asking questions
  - name: 🎯 Contributing Guide
    url: https://github.com/zk-evm/bls12-381/blob/main/CONTRIBUTING.md
    about: Learn how to contribute to this project (read this COMPLETELY before contributing)
