name: 🚀 Feature Request
description: Propose a new feature for the BLS12-381 signature library
title: "[FEATURE]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Feature Request Standards
        
        **High-quality feature requests only.** Vague requests will be closed immediately.
        
        **Required:**
        - Clear use case and motivation
        - Detailed technical specification
        - Performance impact analysis
        - Breaking change assessment
        - Implementation complexity estimate

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Confirm you've done your homework
      options:
        - label: I have read the CONTRIBUTING.md file completely
          required: true
        - label: I have searched existing issues and PRs for similar requests
          required: true
        - label: I have a legitimate use case that cannot be solved with existing APIs
          required: true
        - label: I understand this may require significant development effort
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - New Cryptographic Operation
        - Performance Optimization
        - API Enhancement
        - Build System Improvement
        - Documentation Enhancement
        - Developer Experience
        - Platform Support
        - Other (explain in detail)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature?
      options:
        - Critical (Blocks major use cases, security enhancement)
        - High (Significantly improves existing workflows)
        - Medium (Nice to have, improves some workflows)
        - Low (Minor convenience feature)
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation and Use Case
      description: Why is this feature needed?
      placeholder: |
        **Specific Problem:**
        Describe the exact problem this feature solves.
        
        **Real-World Scenario:**
        Provide concrete examples of where this would be used.
        
        **Current Limitations:**
        What can't you do with the existing API?
        
        **Business Impact:**
        How does this affect actual applications/users?
    validations:
      required: true

  - type: textarea
    id: specification
    attributes:
      label: Technical Specification
      description: Detailed technical requirements
      placeholder: |
        **Proposed API:**
        ```zig
        // Show exactly what the new API would look like
        pub fn newFeature(param1: Type1, param2: Type2) !ReturnType {
            // Implementation details
        }
        ```
        
        **Input/Output Specification:**
        - Input constraints and validation
        - Output format and guarantees
        - Error conditions and handling
        
        **Behavior Specification:**
        - Exact functional requirements
        - Edge case handling
        - Thread safety requirements
        - Memory management contract
    validations:
      required: true

  - type: textarea
    id: performance
    attributes:
      label: Performance Requirements
      description: Performance characteristics and constraints
      placeholder: |
        **Performance Targets:**
        - Expected throughput: X operations/sec
        - Latency requirements: < Y microseconds
        - Memory usage: < Z KB
        
        **Complexity Analysis:**
        - Time complexity: O(?)
        - Space complexity: O(?)
        
        **Benchmarking Plan:**
        How will we measure success of this feature?
    validations:
      required: true

  - type: checkboxes
    id: breaking_changes
    attributes:
      label: Breaking Changes
      description: Does this feature introduce breaking changes?
      options:
        - label: This feature requires breaking changes to existing APIs
        - label: This feature can be implemented without breaking existing APIs
        - label: I'm not sure about breaking changes (needs investigation)

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?
      placeholder: |
        **Alternative 1:**
        - Approach: [Description]
        - Pros: [Benefits]
        - Cons: [Drawbacks]
        - Why rejected: [Reason]
        
        **Alternative 2:**
        - Approach: [Description]
        - Pros: [Benefits]  
        - Cons: [Drawbacks]
        - Why rejected: [Reason]
        
        **Status Quo:**
        Why is doing nothing not acceptable?

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Approach
      description: How would you implement this feature?
      placeholder: |
        **High-Level Design:**
        - Architecture overview
        - Key components involved
        - Integration points
        
        **Implementation Steps:**
        1. Step 1: [Description]
        2. Step 2: [Description]
        3. Step 3: [Description]
        
        **Testing Strategy:**
        - Unit tests required
        - Integration tests needed
        - Performance benchmarks
        - Security considerations
        
        **Complexity Estimate:**
        - Development time: X person-days
        - Lines of code: ~Y lines
        - Risk level: [Low/Medium/High]

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Intent
      description: Are you planning to implement this feature?
      options:
        - label: I plan to implement this feature myself
        - label: I can help with implementation if given guidance
        - label: I'm requesting this feature but cannot implement it
        - label: I need to discuss implementation approach first

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        - References to relevant standards/papers
        - Links to similar implementations
        - Community feedback or support
        - Timeline constraints
        - Integration requirements
